basePath: /
definitions:
  dto.AddImageToPostResponse:
    properties:
      image_id:
        type: string
    type: object
  dto.CreatePostRequest:
    properties:
      author_id:
        type: string
      content:
        type: string
      idempotency_key:
        type: string
      title:
        type: string
    type: object
  dto.CreatePostResponse:
    properties:
      post_id:
        type: string
    type: object
  dto.DeleteImageFromPostResponse:
    properties:
      post_id:
        type: string
    type: object
  dto.EditPostRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  dto.EditPostResponse:
    properties:
      post_id:
        type: string
    type: object
  dto.GetPostsResponse:
    properties:
      posts:
        items:
          $ref: '#/definitions/entities.Post'
        type: array
    type: object
  dto.LoginUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.LoginUserResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user_id:
        type: string
    type: object
  dto.PublishPostRequest:
    properties:
      status:
        type: string
    type: object
  dto.PublishPostResponse:
    properties:
      post_id:
        type: string
    type: object
  dto.RefreshUserTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  dto.RefreshUserTokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.RegistrateUserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
  dto.RegistrateUserResponse:
    properties:
      access_token:
        type: string
      id:
        type: string
      refresh_token:
        type: string
    type: object
  entities.Post:
    properties:
      author_id:
        type: string
      content:
        type: string
      created_at:
        type: string
      idempotency_key:
        type: string
      post_id:
        type: string
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для блога с аутентификацией
  title: Blog API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginUserResponse'
      summary: Залогинить пользователя
      tags:
      - Роли пользователей и аутентификация
  /api/auth/refresh-token:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshUserTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RefreshUserTokenResponse'
      summary: Обновить токен пользователя
      tags:
      - Роли пользователей и аутентификация
  /api/auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegistrateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RegistrateUserResponse'
      summary: Зарегистрировать пользователя
      tags:
      - Роли пользователей и аутентификация
  /api/posts:
    get:
      consumes:
      - application/json
      parameters:
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetPostsResponse'
      summary: Просмотр постов
      tags:
      - Просмотр постов
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные поста
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreatePostRequest'
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreatePostResponse'
      summary: Создать пост
      tags:
      - Управление постами
  /api/posts/{postId}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID поста
        in: path
        name: postId
        required: true
        type: string
      - description: Новое название поста
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.EditPostRequest'
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.EditPostResponse'
      summary: Редактировать пост
      tags:
      - Управление постами
  /api/posts/{postId}/images:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: ID поста
        in: path
        name: postId
        required: true
        type: string
      - description: Картинка
        in: formData
        name: file
        required: true
        type: file
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AddImageToPostResponse'
      summary: Добавить картинку к посту
      tags:
      - Управление постами
  /api/posts/{postId}/images/{imageId}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID поста
        in: path
        name: postId
        required: true
        type: string
      - description: ID картинки
        in: path
        name: imageId
        required: true
        type: string
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.DeleteImageFromPostResponse'
      summary: Удалить картинку из поста
      tags:
      - Управление постами
  /api/posts/{postId}/status:
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID поста
        in: path
        name: postId
        required: true
        type: string
      - description: Статус поста
        in: body
        name: status
        required: true
        schema:
          $ref: '#/definitions/dto.PublishPostRequest'
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PublishPostResponse'
      summary: Опубликовать пост
      tags:
      - Управление постами
swagger: "2.0"
